name: portfolio
description: Fredy's portfolio.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  get_it:
  responsive_builder: ^0.1.4
  provider: ^4.1.2
  stacked: ^1.5.5+1
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.4.10
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
  - family: GoogleSansRegular
    fonts:
      - asset: assets/font/GoogleSansRegular.ttf
